// Generated by CoffeeScript 1.4.0
(function() {
  var a, b, gcd;

  gcd = function(a, b) {
    if (b === 0) {
      return a;
    } else {
      return gcd(b, a % b);
    }
  };

  $("#button").click(function() {});

  a = $("#a").val();

  b = $("#b").val();

  $("#c").html(gcd(a, b));

}).call(this);
