// Generated by CoffeeScript 1.4.0
(function() {
  var _base;

  if (typeof coffeePot !== "undefined" && coffeePot !== null) {
    coffeePot.brew();
  }

  if (typeof coffeePot !== "undefined" && coffeePot !== null) {
    coffeePot.brew();
  }

  if (typeof vehicle.start_engine === "function") {
    if (typeof (_base = vehicle.start_engine()).shift_gear === "function") {
      _base.shift_gear();
    }
  }

}).call(this);
